# Base configs
baseurl: "https://20daban58.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography of Steven Ban"
subtitle: "See the many faces of Steven Ban!"
author: "David Ban"
header:
 title: "Steven"
 subtitle: "David Ban"
footer:
 name: "Hey there, my name is Steven"
 bio: "I am a man who makes many faces"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
